[package]
name = "frontend"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
categories.workspace = true
license.workspace = true
readme.workspace = true
publish.workspace = true

[dev-dependencies]
wasm-bindgen-test = "0.3.19"

[dependencies]
zoon.workspace = true
gloo-worker = { version = "0.4.0", features = ["futures"], default-features = false }
prime-iter = { version = "0.1.0", default-features = false }
pulldown-cmark = { version = "0.9.3", features = ["simd"], default-features = false }
educe = { version = "0.4.22", default-features = true }
