[package]
name = "static_ref_macro"
version = "0.1.0"
authors = ["Martin Kavík <martin@kavik.cz>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = { version = "1.0", default-features = false }
proc-macro2 = { version = "1.0", default-features = false }
