[package]
name = "frontend"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
categories.workspace = true
license.workspace = true
readme.workspace = true
publish.workspace = true

[dev-dependencies]
wasm-bindgen-test = "0.3.19"

[dependencies]
zoon.workspace = true
# @TODO replace `webgl` with `webgpu` once all relevant browsers and WebViews support WebGPU 
# NOTE: Compressed Wasm module with`webgpu` has 125KB, with `webgl` 534KB, see
# https://github.com/gfx-rs/wgpu/issues/1464
wgpu = { version = "0.20.0", features = ["wgsl", "webgl"], default-features = false }
# @TODO switch to `0.30.0` or newer once the integrated examples are updated in their original repos
winit = "0.29.0"
