# port = 8080
port = 8443
# HTTPS is enabled to make the example runnable on mobile browsers -
# cross-origin isolation headers automatically enabled on the Moon backend
# are taken into account by the browser only when served over HTTPS or from the 'localhost' domain.
# Phones are connected through IP to the local dev machine, not through 'localhost'.
https = true
cache_busting = true
backend_log_level = "warn" # "error" / "warn" / "info" / "debug" / "trace"
# required to enable blocking tasks
frontend_multithreading = true

[redirect]
port = 8081
enabled = false

[cors]
origins = ["*"]

[watch]
frontend = [
    "public",
    "frontend/Cargo.toml",
    "frontend/src",
    "../../crates/zoon/Cargo.toml",
    "../../crates/zoon/src",
]
backend = [
    "backend/Cargo.toml",
    "backend/src",
    "../../crates/moon/Cargo.toml",
    "../../crates/moon/src",
]
