[package]
name = "frontend"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
categories.workspace = true
license.workspace = true
readme.workspace = true
publish.workspace = true

[dev-dependencies]
wasm-bindgen-test = "0.3.19"

[dependencies]
zoon.workspace = true
uuid = { version = "1.1.2", features = ["js", "v4", "serde"], default-features = false }
# tauri-bindgen-guest-rust = { git = "https://github.com/tauri-apps/tauri-bindgen", rev = "5eabe7b96c7b77f37d82bd2fe519a9e3e1377c52" }
# tauri-sys = { git = "https://github.com/JonasKruckenberg/tauri-sys", rev = "e8ea8c3fec671fd2edea321ddf3283e4e1505ecb", features = ["event", "tauri"]}
